{{- if .Values.consumer.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template  "saferwall.fullname" . }}-consumer
  labels:
    app.kubernetes.io/name: {{ template "saferwall.name" . }}-consumer
{{ include "saferwall.labels" . | indent 4 }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/name: {{ template "saferwall.name" . }}-consumer
  replicas:  {{ .Values.consumer.replicaCount }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ template "saferwall.name" . }}-consumer
{{ include "saferwall.labels" . | indent 8 }}
    spec:
      {{ if eq .Values.global.privateRegistryServer true }}
      imagePullSecrets:
        - name: regcred
      {{- end }}
      containers:
        - name: "{{ .Values.consumer.name }}"
          image: "{{ .Values.consumer.image.repository }}:{{ .Values.consumer.image.tag }}"
          volumeMounts:
          - name: samples
            mountPath: /samples
          - name:  {{ $.Release.Name }}-consumer-configmap-volume
            mountPath: /consumer/configs/
          resources:
            requests:
              memory: "{{ .Values.consumer.resources.requests.memory }}"
              cpu: "{{ .Values.consumer.resources.requests.cpu }}"
            limits:
              memory: "{{ .Values.consumer.resources.limits.memory }}"
              cpu: "{{ .Values.consumer.resources.limits.cpu }}"
          env:
            - name: SFW_CONSUMER
              value: "prod"
      volumes:
      - name: samples
        persistentVolumeClaim:
          claimName: {{ include "saferwall.fullname" . }}-samples
      - name: {{ $.Release.Name }}-consumer-configmap-volume
        configMap:
          name: {{ include "saferwall.fullname" . }}-consumer
          items:
            - key: consumer_conf
              path: prod.toml
      initContainers:
        - name: wait-for-couchbase
          image: groundnuty/k8s-wait-for:v1.3
          imagePullPolicy: Always
          args:
            - "pod"
            - "-lapp=couchbase"
        - name: wait-for-backend
          image: groundnuty/k8s-wait-for:v1.3
          imagePullPolicy: Always
          args:
            - 'pod'
            - '-lapp.kubernetes.io/name={{ template "saferwall.name" . }}-backend'
{{- end }}
