{{- if .Values.frontend.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template  "saferwall.fullname" . }}-frontend
  labels:
    app.kubernetes.io/name: {{ template "saferwall.name" . }}-frontend
{{ include "saferwall.labels" . | indent 4 }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/name: {{ template "saferwall.name" . }}-frontend
  replicas:  {{ .Values.frontend.replicaCount }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ template "saferwall.name" . }}-frontend
{{ include "saferwall.labels" . | indent 8 }}
    spec:
      {{ if eq .Values.global.privateRegistryServer true }}
      imagePullSecrets:
        - name: regcred
      {{- end }}
      containers:
        - name: "{{ .Values.frontend.name }}"
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          ports:
            - containerPort: {{ .Values.frontend.containerPort }}
          resources:
            requests:
              memory: "{{ .Values.frontend.resources.requests.memory }}"
              cpu: "{{ .Values.frontend.resources.requests.cpu }}"
            limits:
              memory: "{{ .Values.frontend.resources.limits.memory }}"
              cpu: "{{ .Values.frontend.resources.limits.cpu }}"
          env:
            - name: VUE_APP_BACKEND_HOST
              value: "{{ .Values.global.backendHostname }}"
{{- end }}
