{{- if .Values.frontend.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template  "saferwall.fullname" . }}-frontend
  labels:
    app.kubernetes.io/name: {{ template "saferwall.name" . }}-frontend
{{ include "saferwall.labels" . | indent 4 }}
spec:
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/name: {{ template "saferwall.name" . }}-frontend
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.service.targetPort }}
    {{- if .Values.frontend.service.nodePort }}
      nodePort: {{ .Values.frontend.service.nodePort }}
    {{- end }}
  type: {{ .Values.frontend.service.type }}
{{- end }}
