{{- if .Values.multiav.enabled }}
{{- $root := . -}}
{{- range $av, $value := .Values.multiav.vendors }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "saferwall.fullname" $root }}-multiav-{{ $av }}
  labels:
    app.kubernetes.io/name: {{ template "saferwall.name" $root }}-multiav-{{ $av }}
{{ include "saferwall.labels" $root | indent 4 }}
spec:
  selector:
    app.kubernetes.io/instance: {{ $root.Release.Name }}
    app.kubernetes.io/name: {{ template "saferwall.name" $root }}-multiav-{{ $av }}
  ports:
    - port: {{ $value.service.port }}
      targetPort: {{  $value.service.port }}
      protocol: TCP
---
{{- end }}
{{- end }}
