{{- if .Values.multiav.enabled }}
{{- $root := . -}}
{{- range $av, $value := .Values.multiav.vendors }}
{{- if $value.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "saferwall.fullname" $root }}-multiav-{{ $av }}
  labels:
    app.kubernetes.io/name: {{ template "saferwall.name" $root }}-multiav-{{ $av }}
{{ include "saferwall.labels" $root | indent 4 }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ $root.Release.Name }}
      app.kubernetes.io/name: {{ template "saferwall.name" $root }}-multiav-{{ $av }}
  replicas: {{ $value.replicaCount }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ template "saferwall.name" $root }}-multiav-{{ $av }}
{{ include "saferwall.labels" $root | indent 8 }}
    spec:
      {{ if eq $root.Values.global.privateRegistryServer true }}
      imagePullSecrets:
        - name: regcred
      {{- end }}
      containers:
        - name: "{{ $av }}"
          image: "{{ $value.image.repository }}:{{ $value.image.tag }}"
          imagePullPolicy: "{{ $value.image.pullPolicy }}"
          ports:
            - containerPort: {{ $value.containerPort }}
          resources:
            requests:
              cpu: "{{ $root.Values.multiav.resources.requests.cpu }}"
              memory: "{{ $root.Values.multiav.resources.requests.memory }}"
            limits:
              cpu: "{{ $root.Values.multiav.resources.limits.cpu }}"
              memory: "{{ $root.Values.multiav.resources.limits.memory }}"
          volumeMounts:
            - name: samples
              mountPath: /samples
      volumes:
      - name: samples
        persistentVolumeClaim:
          claimName: {{ include "saferwall.fullname" $root }}-samples
---
{{- end }}
{{- end }}
{{- end }}
