apiVersion: v1
kind: Secret
metadata:
  name: cb-admin-secret
type: Opaque
data:
  username: QWRtaW5pc3RyYXRvcg==
  password: cGFzc3dvcmQ=
---
{{ if eq .Values.global.privateRegistryServer true }}
apiVersion: v1
kind: Secret
metadata:
  name: regcred
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOiB7CgkJCSJhdXRoIjogIlB1dCB5b3VyIGF1dGggdG9rZW4gaGVyZSIKCQl9Cgl9LAoJIkh0dHBIZWFkZXJzIjogewoJCSJVc2VyLUFnZW50IjogIkRvY2tlci1DbGllbnQvMTkuMDMuNSAobGludXgpIgoJfQp9
type: kubernetes.io/dockerconfigjson
{{- end }}
