# Possible values "panic", "fatal", "error", "warn", "info", "debug", "trace"
log_level = "warn"
download_dir = "/samples"

[backend]
address = 'http://{{ include "saferwall.fullname" . }}-backend'
admin_user = "Administrator"
admin_pwd = "password"

[ml]
enabled = false
address = 'http://{{ include "saferwall.fullname" . }}-ml'

[nsq]
lookupds = [
{{ $lookupdFullName := printf "%s-nsq-%s" .Release.Name .Values.nsq.nsqlookupd.name -}}
{{ range $i, $e := until (atoi (printf "%d" (int64 .Values.nsq.nsqlookupd.replicaCount))) -}}
    "{{ $lookupdFullName }}-{{ $i }}.{{ $lookupdFullName }}:4161",
{{- end }}]

[minio]
enabled = true
endpoint = '{{ printf "%s-minio" .Release.Name }}:9000'
seckey = "{{ .Values.minio.secretKey }}"
accesskey = "{{ .Values.minio.accessKey }}"
spacename = "{{ .Values.minio.spacename }}"
ssl = false

[multiav]
  enabled = true
  [multiav.vendors]
{{- $root := . -}}
{{- range $av, $value := .Values.multiav.vendors }}
    [multiav.vendors.{{ $av }}]
    enabled = {{ $value.enabled }}
    address = "{{ include "saferwall.fullname" $root }}-multiav-{{ $av }}:50051"
{{- end }}
